### ISSUE TITLE
MacOS build does not contain electron framework

### ISSUE THREAD

**Issue by hjk321** [yancharkin/SpelunkyClassicHDhtml5#10]
```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 52762DF1-0E55-3F8B-9588-8169E6D0EB95
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Spelunky.app/Contents/MacOS/Spelunky Classic HD HTML5
  Reason: no suitable image found.  Did find:
	/Applications/Spelunky.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
```
Full log:
https://pastebin.com/0MmXF57M

**Comment by yancharkin** [comment]
I'm not very familiar with macOS, and I have no access to Mac. I can offer only limited support, but I'll do what I can.
First of all, the build does contain Electron Framework but, for some reason, it is unusable. Before uploading, I tested the build (on macOS 10.10 or 10.11, not sure), and it worked fine. Either something wrong with your system or (more likely) the Electron version included in the build incompatible with recent macOS.

I'm going to update builds to a more recent Electron version, but it may take some time (besides, I can't test macOS build anyway). So if you willing to spend some time, I suggest you not wait and try the following:
- download prebuilt Electron binaries from here  (you can try different versions): https://github.com/electron/electron/releases
- download this archive: https://mega.nz/file/el5EVQbY#OZEqiSH8XAmgDcZyKai60u2jF8pKZUc35Rqv93MhTc0
- extract both archives and place 'app' directory from the second archive to 'Electron.app/Contents/Resources/'
- execute 'Electron.app'

**Comment by yancharkin** [comment]
@hjk321 Hello?

**Comment by yancharkin** [comment]
The new build includes the latest Electron. It will be nice if you test it.
https://github.com/yancharkin/SpelunkyClassicHDhtml5/releases

**Comment by hjk321** [comment]
Sorry for the late response.

Unfortunately, the crash still persists with the same error for 1.1.5 - the embedded electron file is "too short."
This is an Intel Mac on Big Sur. I cannot test on Silicon.

(Additionally, the executable was improperly chmodded, which is unrelated but still of note.)

**Comment by yancharkin** [comment]
It looks like you have the same issue: https://github.com/electron-userland/electron-builder/issues/3674

**Comment by yancharkin** [comment]
The simplest solution is to use different software to unpack the zip file.

If it doesn't help:
- download Electron binaries from [here](https://github.com/electron/electron/releases) (you can try different versions)
- download **spelunky_classic_hd_html5-electron_ready.zip** from the [releases page](https://github.com/yancharkin/SpelunkyClassicHDhtml5/releases)
- extract both archives and place the content of the second archive into the **'Electron.app/Contents/Resources/app/'** directory
- execute **'Electron.app'**

Maybe I can solve this issue by repacking the archive with different software, but I do not own Mac and can't test it. If someone is willing to help, drop me a line.
