### ISSUE TITLE
How to run html file on ChromeOS [the game doesn't work]

### ISSUE THREAD

**Issue by Reznar705** [yancharkin/SpelunkyClassicHDhtml5#29]
when running the source code zip file it simply plays a looping animation, not the game

**Comment by yancharkin** [comment]
As I already told you, it's unlikely that you can play the game just by opening the html file in a browser. You need to start a webserver. Or [better] learn how to launch Linux apps on the ChromeOS.

**Comment by Reznar705** [comment]
i have done lots of research, and have concluded i don't know what i'm doing but i don't think it's possible to launch linux apps other than .deb files


(also thanks for making this version of spelunky classic it's awesome)

**Comment by yancharkin** [comment]
I'm pretty sure, you can run .AppImage:
https://www.google.com/search?q=run+appimage+on+chromeos

Also, if your Chromebook has x86_64 processor (not ARM), there is a chance that it is possible to launch regular non html5 version.

**Comment by yancharkin** [comment]
@Reznar705 If you are still interested, the game is now available as PWA, so you can install it on your Chromebook.
 [More info and installation instructions are here.](https://github.com/yancharkin/SpelunkyClassicHDhtml5/blob/gh-pages/README.md)
